//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// VE.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define CG_IDR_POPUP_LEFT_VIEW          102
#define CG_IDR_POPUP_VEVIEW             103
#define IDR_EDIT_MENU                   103
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    104
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 105
#define CG_IDS_CANNOT_OPEN_CLIPBOARD1   106
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA1 107
#define IDS_PROPSHT_CAPTION             108
#define IDS_MDL_PROPSHT_CAPTION         108
#define IDD_PROPPAGE1                   109
#define IDD_MPROPPAGE1                  109
#define IDS_PAD_PROPSHT_CAPTION         109
#define IDD_PPROPPAGE1                  111
#define CG_IDR_POPUP_CLASS_VIEW         112
#define CG_IDS_CANNOT_OPEN_CLIPBOARD2   113
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA2 114
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DPTYPE                      130
#define CG_IDR_POPUP_VARVIEW            132
#define ID_WINDOW_MANAGER               131
#define IDD_VAR                         133
#define IDD_OPTION                      136
#define IDD_CLS                         139
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDC_MNAME                       1000
#define IDC_MNUMPADFS                   1001
#define IDC_PADTYPE1                    1003
#define IDC_PT1                         1003
#define IDC_PADTYPE2                    1004
#define IDC_PT3                         1004
#define IDC_PADSTR                      1005
#define IDC_PADTYPE3                    1006
#define IDC_PT6                         1006
#define IDC_PADTYPE0                    1007
#define IDC_PT0                         1007
#define IDC_PT2                         1008
#define IDC_PT4                         1009
#define IDC_PT5                         1010
#define IDC_PADCOMMENT                  1011
#define IDC_CASE                        1012
#define IDC_MARG                        1013
#define IDC_MRET                        1014
#define IDC_MRET_TYPE                   1014
#define IDC_MRET_POINTER                1015
#define IDC_MACCESSTYPE                 1016
#define IDC_NAME                        1017
#define IDC_START                       1018
#define IDC_COMMENT                     1019
#define IDC_SCOPE                       1020
#define IDC_MRECURSIVE                  1022
#define IDC_MCOMMENT                    1024
#define IDC_MNUM_VARS                   1025
#define IDC_TYPE                        1026
#define IDC_KIND                        1029
#define IDC_POINTER                     1032
#define IDC_VC_ENV                      1036
#define IDC_VC                          1037
#define IDC_VC2010                      1037
#define IDC_VC60                        1038
#define IDC_VC_OTHER                    1039
#define IDC_PATH                        1040
#define IDC_PATH_BROWSE                 1041
#define IDC_MRET_STRUCT                 1043
#define IDC_VC_ENV2008                  1044
#define IDC_CLSTYPE                     1046
#define IDC_CNAME                       1047
#define IDC_STRUCT                      1050
#define IDC_ACCESSTYPE                  1051
#define IDC_BASECLASS                   1054
#define IDC_FRIENDCLASS                 1055
#define IDC_MINLINE                     1057
#define IDC_MFUNCTYPE                   1058
#define IDC_CNUMVAR                     1060
#define IDC_CNUMFUNC                    1061
#define ID_INSERT                       32771
#define ID_VAR                          32771
#define ID_PROPERTY                     32772
#define ID_PADPROPERTY                  32772
#define ID_MDL                          32772
#define ID_PROC                         32773
#define ID_IF                           32774
#define ID_PROPERTIES                   32775
#define ID_SELECT                       32775
#define ID_RENSETSU                     32776
#define ID_PROCESS                      32776
#define ID_FOR                          32776
#define ID_SELECTION                    32777
#define ID_DOWHILE                      32777
#define ID_REPEAT                       32778
#define ID_COMMENT                      32779
#define ID_BUTTON32780                  32780
#define ID_EDIT_DELETE                  32781
#define ID_MENUITEM32782                32782
#define IDC_TEST                        32783
#define ID_EXEC                         32785
#define ID_EDIT_DELETE_M                32786
#define ID_EDIT_DELETE_P                32787
#define ID_WHILE                        32790
#define ID_INSERT_MODULE                32792
#define ID_MENUITEM32793                32793
#define ID_VIEW_ADJUST                  32794
#define ID_FILE_SOURCE                  32801
#define ID_INSERT_M                     32803
#define ID_TOOL_OPTION                  32804
#define ID_EDIT_PASTE_P                 32805
#define ID_INSERTPADF                   32806
#define ID_INSERT_PADF                  32807
#define ID_SAVE_SOURCE_FILE             32808
#define ID_INSERT_VAR                   32809
#define ID_VAR_PROPERTY                 32811
#define ID_LINE                         32813
#define ID_INSERT_IF                    32815
#define ID_INSERT_SWITCH                32816
#define ID_INSERT_FOR                   32817
#define ID_INSERT_WHILE                 32818
#define ID_INSERT_DO_WHILE              32819
#define ID_INSERT_PROCESS               32822
#define ID_INSERT_COMMENT               32830
#define ID_COMPILE                      32832
#define ID_BUILD_BUILD                  32835
#define ID_BUILD_COMPILE                32836
#define ID_BUILD_EXEC                   32838
#define ID_INSERT_CLS                   32840
#define ID_CLS_PROPERTY                 32841

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
